### PR TITLE
Adding design patterns to EO

### PR DESCRIPTION
**Pull request by cmungall**
Creating a PR for @marieALaporte's branch

### CODE REVIEW

**Comment by cmungall** [comment]
I made the PR so I can't review, but I say +1

**Comment by marieALaporte** [comment]
The existing pattern will need to be updated and more need to be added based on what we decide.

@cmungall in the makefile, I don't know how this is supposed to work for importing the pattern file into the main file... should this be part of the release process only? I haven't added the robot merge command so far, as I was not sure of where this should fit in the process 

Just as a reminder, the PURL will have to point to the eo.owl (or eo.obo) file that will be created by the release process. No release process has been run yet

Last thing, before to accept the PR, should we take the opportunity, as we are almost starting from scratch, to organize the repo as the other OBO Foundry repos?

**Comment by marieALaporte** [comment]
the .owl file will need to be updated by Justin's cron job - not in sync with the .obo file of this PR

**Comment by marieALaporte** [comment]
A comment on what is part of the eo.tvs file: I only tried to create the patterns for the classes that would need to be linked to the TO. That's the reason why not all the EO treatment classes are listed. I haven't tried to map all of them to CHEBI and  NCBI.

**Comment by cmungall** [comment]
> the .owl file will need to be updated by Justin's cron job - not in sync with the .obo file of this PR

@elserj I think we can remove the cron job. We can have this repo follow the standard SOP for all manually released ontologies - the release manager/ontology editor does a `make release` which builds owl and obo release files, which are committed and pushed.

See for example the template we often use: https://github.com/cmungall/ontology-starter-kit/blob/master/template/src/ontology/README-editors.md#release-manager-notes

**Comment by cmungall** [comment]
@DoctorBud can we go a TE demo for this as well? Files in this branch: https://github.com/Planteome/plant-environment-ontology/tree/test-dp

**Pull request merged**
